# Temporal periods
TEMPORAL_PERIOD_WEEK = 'week'
TEMPORAL_PERIOD_MONTH = 'month'
TEMPORAL_PERIOD_YEAR = 'year'
VALID_TEMPORAL_PERIODS = [TEMPORAL_PERIOD_WEEK, TEMPORAL_PERIOD_MONTH, TEMPORAL_PERIOD_YEAR]

# Types
VALID_DATE_TYPE = 'datetime64[ns]'
VALID_FLOAT_TYPE = 'float64'
VALID_INTEGER_TYPE = 'int64'
VALID_STRING_TYPE = 'object'
VALID_CATEGORICAL_TYPE = 'category' # ?
# TODO: check categorical instead of R factor
VALID_TYPES_WITHOUT_DATE = [VALID_INTEGER_TYPE, VALID_STRING_TYPE, VALID_FLOAT_TYPE, VALID_CATEGORICAL_TYPE]  # Pandas types
VALID_TYPES = VALID_TYPES_WITHOUT_DATE + [VALID_DATE_TYPE]  # Pandas types
