name: Publish to PyPI

# This workflow triggers when a new release is published on GitHub.
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          pip install --upgrade build twine

      - name: Build the package
        run: python -m build

      - name: Publish package to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive --username __token__ --password $PYPI_API_TOKEN dist/*
